# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: circleci/node:10.15.3-browsers

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm build
          - npm run citest
          # - npm install tslint
          - ./node_modules/.bin/tslint --config ./tslint.json --project ./tsconfig.app.json
          # - cd /Users/zachary.temple/agvance-workspace/base/CasinoRoyale && ./node_modules/.bin/tslint --config ./tslint.json --project ./tsconfig.app.json
